### ISSUE TITLE
Witch-hunt: 㝮 does not display despite markup

### ISSUE THREAD

**Issue by Kryomancer** [umineko-project/umineko-scripting#10]
Game language: Witch-Hunt (umineko-wh-scripts_r3610)
Operating system: Windows (onscripter-ru_win_r3567)
Episode and chapter where the issue occurs:  Ep 5 Ch 5, specifically the lines

https://github.com/umineko-project/umineko-scripting/blob/dcf20145a7fba41097526a650b4481b83131f617/story/ep5/wh/umi5_5.txt#L545
https://github.com/umineko-project/umineko-scripting/blob/dcf20145a7fba41097526a650b4481b83131f617/story/ep5/wh/umi5_5.txt#L557

Description of the issue: The kanji 㝮 does not display and is instead shown as a crossed over box. This time I have no clue how to fix this since at least to me it seems to be surrounded by the correct markup unlike the past cases of problematic kanji in the WH translation. I checked the fonts the game uses and the kanji is available there. These are the only two occurrences of this specific kanji in the `story/ep*/wh/` folders.

![screenshot](https://i.imgur.com/fN7zl9M.png)

**Comment by ooa113y** [comment]
Quite honestly I have no clue why that kanji is even there, it's supposed to be the の (no) kana. I've fixed it accordingly. Unfortunately I cannot answer the question of why the character itself doesn't render properly.

**Comment by vit9696** [comment]
@ooa113y there is one more issue with this example actually. In order to provide smart quotes for English language including nested smart quotes with the possibility of having an apostrophe (`'`) within the text we introduced a separate smart quote system. So you write `"Text "text" text."` and get `“Text ‘text’ text.”`. Unsure if you want to fix it, but you might.

**Comment by ooa113y** [comment]
Ah, that's a cool feature. I think I'd have to go through the entire script to fix this, unfortunately. When Witch-Hunt was implementing their official TL they were using ponscripter which doesn't have any smart quoting, so they just used `"` for character dialogue and `'` for quotation marks inside the dialogue, which is the same as the apostrophe character. So I can't think of a coherent way to match single-quotes without also matching apostrophes off the top of my head, but I'll keep this in mind and see if I can come up with something eventually.

**Comment by ooa113y** [comment]
I believe I found a way to fix this in c2e7782b1e8e052724e202c95aec5529dae11122, however, I may have accidently grabbed some unnecessary stuff, which if discovered I'll fix later. In particular, Hideyoshi and Jessica's speech patterns include a lot of words like `'cause` and whatnot, which may have been mistakenly interpreted as single-quotes rather than apostrophes. I have cleaned the replacement from those *at a glance*, so most of them should be fine, but I may have missed a few.
