### ISSUE TITLE
Text placement

### ISSUE THREAD

**Issue by Leukemiya** [umineko-project/umineko-scripting#20]
Game language: Witch-Hunt

Operating system: Windows

Episode and chapter where the issue occurs: Assuming everywhere

Description of the issue: All the in-game Witch-Hunt text is displayed slightly higher in comparison to the English text, which I consider to be displayed properly. I do not believe this is intentional, nor have I found any other bug report about it, thus why I'm posting this one. I've made the following image comparing the two, so that the issue is clear to see.

Screenshot of the issue:
![image](https://user-images.githubusercontent.com/75042773/100278544-b89a6900-2f6d-11eb-9457-caa7bee4e34b.png)

**Comment by ooa113y** [comment]
You are comparing the current version of the WH script with an older version of the EN script (what seems to be the current publicly stable release). If you were to use the latest development version fo the EN script, you'd see the same thing.
![image](https://user-images.githubusercontent.com/462484/100281302-b68ad700-2f7a-11eb-9678-6a7500dbe3f0.png)
In the future, please pay attention to the version number in the title bar when comparing scripts and make sure you have the same revision on both, otherwise you may end up running into more non-existent issues 😄 
The change comes from [here](https://github.com/umineko-project/umineko-scripting/commit/be747fdb#diff-97ed45b371da44af8dbed98c37545c6081f2dc23315d7cb619392000a595d369R32284), if you are curious. I am not sure what the actual reasoning behind it was, though.

**Comment by vit9696** [comment]
The origin of the change is [Kuwadorian 333](https://forum.umineko-project.org/viewtopic.php?f=9&t=333). After more detailed comparison with the PS3 we discovered that our initial text positioning was wrong, so that got fixed but that change.

**Comment by ooa113y** [comment]
> [Kuwadorian 333](https://forum.umineko-project.org/viewtopic.php?f=9&t=333)

Just as an FYI but this link leads to a private forum that not even I am authorised to access, and I'm almost certain the original submitter of the issue wouldn't have rights for it either 😆 
That said, the explanation you have provided makes enough sense on its own, so thanks for explaining.

**Comment by Leukemiya** [comment]
Thank you for the immensely helpful quick reply.  Much to my mistake, I only checked for the version of my WH script before making my assessment and posting. I had also failed to check the other text box types, which indeed present no issues. Thank you again and sorry for being a bother.
